### ISSUE TITLE
Problemas ao executar o código por conta de versão do SQLAlchemy e Pandas

### ISSUE THREAD

**Issue by gguiesi** [TeoCalvo/dtona#8]
Eu tive problemas para executar o código por conta da versão do SQLAlchemy e Pandas. Hoje os pacotes mais recentes dão problema ao executar. Por conta disso pode ser interessante inserir o aquivo requeriments.txt com as versões corretas.
As que funcionaram para mim:

- pandas                    2.1.4
- sqlalchemy            1.4.49

**Comment by TeoCalvo** [comment]
Arquivo de `requirements.txt` definido no commit: https://github.com/TeoCalvo/dtona/commit/e40dccb84eb50835713274b03af65d435332770d
